[package]
name = "aoc_2022"
version = "0.1.0"
authors = ["RoccoDev <hey@rocco.dev>"]
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1"
fxhash = "0.2.1"
rayon = "1"
enum-map = "2.4"

[profile.release]
lto = true
codegen-units = 1
